### ISSUE TITLE
What is .type extension?

### ISSUE THREAD

**Issue by region23** [radovskyb/go-packages#1]
What is `.type` extension of files?
e.g. this https://github.com/radovskyb/go-packages/blob/master/url/url.type

**Comment by radovskyb** [comment]
Hey @pavlik, it's not a real extension. For some of the package's, when I started learning Go, I created some files which I gave the extension `.type`, simply for a reference to be able to easily see type definitions of objects or interfaces. For example, for an `http.Client` object, I might have created a `client.type` file, which simply contained the type definition of an `http.Client` struct.

**Comment by pavlik** [comment]
@radovskyb thanks for the answer
